\doxysection{Référence de la classe django.\+contrib.\+sessions.\+backends.\+base.\+Create\+Error}
\hypertarget{classdjango_1_1contrib_1_1sessions_1_1backends_1_1base_1_1CreateError}{}\label{classdjango_1_1contrib_1_1sessions_1_1backends_1_1base_1_1CreateError}\index{django.contrib.sessions.backends.base.CreateError@{django.contrib.sessions.backends.base.CreateError}}


Graphe d\textquotesingle{}héritage de django.\+contrib.\+sessions.\+backends.\+base.\+Create\+Error\+:
% FIG 0


Graphe de collaboration de django.\+contrib.\+sessions.\+backends.\+base.\+Create\+Error\+:
% FIG 1


\doxysubsection{Description détaillée}
\begin{DoxyVerb}Used internally as a consistent exception type to catch from save (see the
docstring for SessionBase.save() for details).
\end{DoxyVerb}
 

La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/django/contrib/sessions/backends/\mbox{\hyperlink{django_2contrib_2sessions_2backends_2base_8py}{base.\+py}}\end{DoxyCompactItemize}
