\doxysection{Référence de la classe numpy.\+exceptions.\+Too\+Hard\+Error}
\hypertarget{classnumpy_1_1exceptions_1_1TooHardError}{}\label{classnumpy_1_1exceptions_1_1TooHardError}\index{numpy.exceptions.TooHardError@{numpy.exceptions.TooHardError}}


Graphe d\textquotesingle{}héritage de numpy.\+exceptions.\+Too\+Hard\+Error\+:
% FIG 0


Graphe de collaboration de numpy.\+exceptions.\+Too\+Hard\+Error\+:
% FIG 1


\doxysubsection{Description détaillée}
\begin{DoxyVerb}max_work was exceeded.

This is raised whenever the maximum number of candidate solutions
to consider specified by the ``max_work`` parameter is exceeded.
Assigning a finite number to max_work may have caused the operation
to fail.\end{DoxyVerb}
 

La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/numpy/\mbox{\hyperlink{numpy_2exceptions_8py}{exceptions.\+py}}\end{DoxyCompactItemize}
