\doxysection{Référence de la classe numpy.\+exceptions.\+Axis\+Error}
\hypertarget{classnumpy_1_1exceptions_1_1AxisError}{}\label{classnumpy_1_1exceptions_1_1AxisError}\index{numpy.exceptions.AxisError@{numpy.exceptions.AxisError}}


Graphe d\textquotesingle{}héritage de numpy.\+exceptions.\+Axis\+Error\+:
% FIG 0


Graphe de collaboration de numpy.\+exceptions.\+Axis\+Error\+:
% FIG 1
\doxysubsubsection*{Fonctions membres publiques}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classnumpy_1_1exceptions_1_1AxisError_af738185ad5e15cd207eea185718b6eb7}{\+\_\+\+\_\+init\+\_\+\+\_\+}} (self, \mbox{\hyperlink{classnumpy_1_1exceptions_1_1AxisError_a603757bcd5b2e62910066dc7ef8bb02e}{axis}}, \mbox{\hyperlink{classnumpy_1_1exceptions_1_1AxisError_a4ef6a2160626f702a86e1c78e77bc79a}{ndim}}=None, msg\+\_\+prefix=None)
\item 
\mbox{\hyperlink{classnumpy_1_1exceptions_1_1AxisError_aa4ca682e6898c473e629a578bc0d642a}{\+\_\+\+\_\+str\+\_\+\+\_\+}} (self)
\end{DoxyCompactItemize}
\doxysubsubsection*{Attributs publics}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classnumpy_1_1exceptions_1_1AxisError_a603757bcd5b2e62910066dc7ef8bb02e}{axis}}
\item 
\mbox{\hyperlink{classnumpy_1_1exceptions_1_1AxisError_a4ef6a2160626f702a86e1c78e77bc79a}{ndim}}
\end{DoxyCompactItemize}
\doxysubsubsection*{Attributs protégés}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classnumpy_1_1exceptions_1_1AxisError_a4c221d3e17788dc75fde3e7b08699918}{\+\_\+msg}}
\end{DoxyCompactItemize}


\doxysubsection{Description détaillée}
\begin{DoxyVerb}Axis supplied was invalid.

This is raised whenever an ``axis`` parameter is specified that is larger
than the number of array dimensions.
For compatibility with code written against older numpy versions, which
raised a mixture of :exc:`ValueError` and :exc:`IndexError` for this
situation, this exception subclasses both to ensure that
``except ValueError`` and ``except IndexError`` statements continue
to catch ``AxisError``.

Parameters
----------
axis : int or str
    The out of bounds axis or a custom exception message.
    If an axis is provided, then `ndim` should be specified as well.
ndim : int, optional
    The number of array dimensions.
msg_prefix : str, optional
    A prefix for the exception message.

Attributes
----------
axis : int, optional
    The out of bounds axis or ``None`` if a custom exception
    message was provided. This should be the axis as passed by
    the user, before any normalization to resolve negative indices.

    .. versionadded:: 1.22
ndim : int, optional
    The number of array dimensions or ``None`` if a custom exception
    message was provided.

    .. versionadded:: 1.22


Examples
--------
>>> import numpy as np
>>> array_1d = np.arange(10)
>>> np.cumsum(array_1d, axis=1)
Traceback (most recent call last):
  ...
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1

Negative axes are preserved:

>>> np.cumsum(array_1d, axis=-2)
Traceback (most recent call last):
  ...
numpy.exceptions.AxisError: axis -2 is out of bounds for array of dimension 1

The class constructor generally takes the axis and arrays'
dimensionality as arguments:

>>> print(np.exceptions.AxisError(2, 1, msg_prefix='error'))
error: axis 2 is out of bounds for array of dimension 1

Alternatively, a custom exception message can be passed:

>>> print(np.exceptions.AxisError('Custom error message'))
Custom error message\end{DoxyVerb}
 

\doxysubsection{Documentation des constructeurs et destructeur}
\Hypertarget{classnumpy_1_1exceptions_1_1AxisError_af738185ad5e15cd207eea185718b6eb7}\label{classnumpy_1_1exceptions_1_1AxisError_af738185ad5e15cd207eea185718b6eb7} 
\index{numpy.exceptions.AxisError@{numpy.exceptions.AxisError}!\_\_init\_\_@{\_\_init\_\_}}
\index{\_\_init\_\_@{\_\_init\_\_}!numpy.exceptions.AxisError@{numpy.exceptions.AxisError}}
\doxysubsubsection{\texorpdfstring{\_\_init\_\_()}{\_\_init\_\_()}}
{\footnotesize\ttfamily numpy.\+exceptions.\+Axis\+Error.\+\_\+\+\_\+init\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self,  }\item[{}]{axis,  }\item[{}]{ndim = {\ttfamily None},  }\item[{}]{msg\+\_\+prefix = {\ttfamily None} }\end{DoxyParamCaption})}



\doxysubsection{Documentation des fonctions membres}
\Hypertarget{classnumpy_1_1exceptions_1_1AxisError_aa4ca682e6898c473e629a578bc0d642a}\label{classnumpy_1_1exceptions_1_1AxisError_aa4ca682e6898c473e629a578bc0d642a} 
\index{numpy.exceptions.AxisError@{numpy.exceptions.AxisError}!\_\_str\_\_@{\_\_str\_\_}}
\index{\_\_str\_\_@{\_\_str\_\_}!numpy.exceptions.AxisError@{numpy.exceptions.AxisError}}
\doxysubsubsection{\texorpdfstring{\_\_str\_\_()}{\_\_str\_\_()}}
{\footnotesize\ttfamily numpy.\+exceptions.\+Axis\+Error.\+\_\+\+\_\+str\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self }\end{DoxyParamCaption})}



\doxysubsection{Documentation des données membres}
\Hypertarget{classnumpy_1_1exceptions_1_1AxisError_a4c221d3e17788dc75fde3e7b08699918}\label{classnumpy_1_1exceptions_1_1AxisError_a4c221d3e17788dc75fde3e7b08699918} 
\index{numpy.exceptions.AxisError@{numpy.exceptions.AxisError}!\_msg@{\_msg}}
\index{\_msg@{\_msg}!numpy.exceptions.AxisError@{numpy.exceptions.AxisError}}
\doxysubsubsection{\texorpdfstring{\_msg}{\_msg}}
{\footnotesize\ttfamily numpy.\+exceptions.\+Axis\+Error.\+\_\+msg\hspace{0.3cm}{\ttfamily [protected]}}

\Hypertarget{classnumpy_1_1exceptions_1_1AxisError_a603757bcd5b2e62910066dc7ef8bb02e}\label{classnumpy_1_1exceptions_1_1AxisError_a603757bcd5b2e62910066dc7ef8bb02e} 
\index{numpy.exceptions.AxisError@{numpy.exceptions.AxisError}!axis@{axis}}
\index{axis@{axis}!numpy.exceptions.AxisError@{numpy.exceptions.AxisError}}
\doxysubsubsection{\texorpdfstring{axis}{axis}}
{\footnotesize\ttfamily numpy.\+exceptions.\+Axis\+Error.\+axis}

\Hypertarget{classnumpy_1_1exceptions_1_1AxisError_a4ef6a2160626f702a86e1c78e77bc79a}\label{classnumpy_1_1exceptions_1_1AxisError_a4ef6a2160626f702a86e1c78e77bc79a} 
\index{numpy.exceptions.AxisError@{numpy.exceptions.AxisError}!ndim@{ndim}}
\index{ndim@{ndim}!numpy.exceptions.AxisError@{numpy.exceptions.AxisError}}
\doxysubsubsection{\texorpdfstring{ndim}{ndim}}
{\footnotesize\ttfamily numpy.\+exceptions.\+Axis\+Error.\+ndim}



La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/numpy/\mbox{\hyperlink{numpy_2exceptions_8py}{exceptions.\+py}}\end{DoxyCompactItemize}
