\doxysection{Référence de la classe django.\+contrib.\+gis.\+geos.\+error.\+GEOSException}
\hypertarget{classdjango_1_1contrib_1_1gis_1_1geos_1_1error_1_1GEOSException}{}\label{classdjango_1_1contrib_1_1gis_1_1geos_1_1error_1_1GEOSException}\index{django.contrib.gis.geos.error.GEOSException@{django.contrib.gis.geos.error.GEOSException}}


Graphe d\textquotesingle{}héritage de django.\+contrib.\+gis.\+geos.\+error.\+GEOSException\+:
% FIG 0


Graphe de collaboration de django.\+contrib.\+gis.\+geos.\+error.\+GEOSException\+:
% FIG 1


La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/django/contrib/gis/geos/\mbox{\hyperlink{geos_2error_8py}{error.\+py}}\end{DoxyCompactItemize}
