\doxysection{Référence de la classe django.\+core.\+exceptions.\+Synchronous\+Only\+Operation}
\hypertarget{classdjango_1_1core_1_1exceptions_1_1SynchronousOnlyOperation}{}\label{classdjango_1_1core_1_1exceptions_1_1SynchronousOnlyOperation}\index{django.core.exceptions.SynchronousOnlyOperation@{django.core.exceptions.SynchronousOnlyOperation}}


Graphe d\textquotesingle{}héritage de django.\+core.\+exceptions.\+Synchronous\+Only\+Operation\+:
% FIG 0


Graphe de collaboration de django.\+core.\+exceptions.\+Synchronous\+Only\+Operation\+:
% FIG 1


\doxysubsection{Description détaillée}
\begin{DoxyVerb}The user tried to call a sync-only function from an async context.\end{DoxyVerb}
 

La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/django/core/\mbox{\hyperlink{django_2core_2exceptions_8py}{exceptions.\+py}}\end{DoxyCompactItemize}
