\doxysection{Référence du fichier env/lib/python3.12/site-\/packages/django/contrib/gis/geos/error.py}
\hypertarget{geos_2error_8py}{}\label{geos_2error_8py}\index{env/lib/python3.12/site-\/packages/django/contrib/gis/geos/error.py@{env/lib/python3.12/site-\/packages/django/contrib/gis/geos/error.py}}
\doxysubsubsection*{Classes}
\begin{DoxyCompactItemize}
\item 
class \mbox{\hyperlink{classdjango_1_1contrib_1_1gis_1_1geos_1_1error_1_1GEOSException}{django.\+contrib.\+gis.\+geos.\+error.\+GEOSException}}
\end{DoxyCompactItemize}
\doxysubsubsection*{Espaces de nommage}
\begin{DoxyCompactItemize}
\item 
namespace \mbox{\hyperlink{namespacedjango}{django}}
\item 
namespace \mbox{\hyperlink{namespacedjango_1_1contrib}{django.\+contrib}}
\item 
namespace \mbox{\hyperlink{namespacedjango_1_1contrib_1_1gis}{django.\+contrib.\+gis}}
\item 
namespace \mbox{\hyperlink{namespacedjango_1_1contrib_1_1gis_1_1geos}{django.\+contrib.\+gis.\+geos}}
\item 
namespace \mbox{\hyperlink{namespacedjango_1_1contrib_1_1gis_1_1geos_1_1error}{django.\+contrib.\+gis.\+geos.\+error}}
\end{DoxyCompactItemize}
